server:
  port: 9090

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${xl.datasource.driver-class-name}
      url: jdbc:mysql://${xl.datasource.host}:${xl.datasource.port}/${xl.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${xl.datasource.username}
      password: ${xl.datasource.password}

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto  # 使用数据库自增
xl:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: xiaolin
    user-secret-key: xiaoru
    # 设置jwt过期时间
    admin-ttl: 7200000
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-token-name: token
  alioss:
    endpoint: ${xl.alioss.endpoint}
    bucket-name: ${xl.alioss.bucket-name}

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    property:
      prefix: ENC(
      suffix: )